#ifndef GRAPHICS_COLORS_H
#define GRAPHICS_COLORS_H

#define FRAMEBUFFER_BLACK 0x00
#define FRAMEBUFFER_BLUE 0x01
#define FRAMEBUFFER_GREEN 0x02
#define FRAMEBUFFER_CYAN 0x03
#define FRAMEBUFFER_RED 0x04
#define FRAMEBUFFER_MAGENTA 0x05
#define FRAMEBUFFER_BROWN 0x06
#define FRAMEBUFFER_LIGHT_GRAY 0x07
#define FRAMEBUFFER_DARK_GRAY 0x08
#define FRAMEBUFFER_LIGHT_BLUE 0x09
#define FRAMEBUFFER_LIGHT_GREEN 0x0A
#define FRAMEBUFFER_LIGHT_CYAN 0x0B
#define FRAMEBUFFER_LIGHT_RED 0x0C
#define FRAMEBUFFER_LIGHT_MAGENTA 0x0D
#define FRAMEBUFFER_YELLOW 0x0E
#define FRAMEBUFFER_WHITE 0x0F

#endif /* ! GRAPHICS_COLORS_H */
